### PR TITLE
Update requirements.txt. Add missing dependency.

### PR DESCRIPTION
**Pull request by adolli**
I see you import the module `win32api` in your code https://github.com/pywinauto/pywinauto/blob/fd27458700026f283a23e176bcd7303b68bb5077/pywinauto/mouse.py#L40

### CODE REVIEW

**Comment by vasily-v-ryabov** [comment]
Thanks for trying. But it looks like a small misunderstanding.

As far as I remember, this `requirements.txt` is used for ReadTheDocs only. It runs on some Linux and pyWin32 is not needed there. Maybe renaming to `doc-requirements.txt` make some sense, but together with ReadTheDocs project change.

`dev-requirements.txt` is used for AppVeyor CI on Windows Server and it contains `pypiwin32` (this is the correct name on PyPI).

Official requirements (for `pip install pywinauto`) are all in `setup.py`. So if you put only `pywinauto` to your local `requirements.txt` it will pull all the dependencies and you don't need to put `comtypes` or `six` there.

**Comment by adolli** [comment]
Sorry for my not considering other platforms. When I try to install pywinauto in virtualenv, the `win32api` is still missing. I see that the dependency is appended dynamically in setup.py. 
https://github.com/pywinauto/pywinauto/blob/master/setup.py#L61-L64

Is there any incompatibility with virtualenv?

**Comment by vasily-v-ryabov** [comment]
Ah, I see. We don't run auto tests in virtualenv. If this is virtualenv specific, it's new finding!

**Comment by adolli** [comment]
I am not sure why it skips installing pypiwin32, not very familiar with virtualenv.

**Comment by vasily-v-ryabov** [comment]
Hmm... I've just figured out that pypiwin32 package became obsolete and pywin32 is now an official PyPI package again. Going to fix it in `setup.py` in next pywinauto update.

**Comment by adolli** [comment]
cool~

**Pull request closed without merging**
