### PR TITLE
Converted ActionLogger().log commands from print style to string concat

### PR DESCRIPTION
**Pull request by TomRobo237**
Fixed Action logging in print style by swapping to strings as described in issue #798

### CODE REVIEW

**Comment by airelil** [comment]
Thanks for the contribution! As I understand, we didn't bump into the problem before because this piece of code never was executed.  Ideally, l'd like to see a unit test for the case.

**Comment by TomRobo237** [comment]
Hmmm, writing that may be a little beyond me at this point. I've only really begun to play around with some of the pywinauto features. I'm not sure what I would write to hit that code block tbh.

**Comment by pakal** [comment]
Nice, the PR seems to solve the problem (although %-formatting or str.format() would be more readable, but I'm nitpicking).

Indeed managing to trigger an OS error on remote process WriteProcessMemory() is not easy, does anyone know how/when it can happen ?

**Comment by airelil** [comment]
I, usually just use 'mock' to return the errors I need to get to hit the code. There are several examples for mock usage in unittests directory.

**Comment by vasily-v-ryabov** [comment]
Thanks for the fix. It aligns all such statements across the module. So I decided to merge it without unit tests. It seems not a critical point for this rare case.

**Comment by vasily-v-ryabov** [comment]
@pakal `WriteProcessMemory` usually fails when calling it in low privilege process trying to write into admin process. But recent pywinauto versions do all checks for running Python as administrator when connecting to admin-privileged process. So this particular case may be more interesting.

**Pull request merged**
