### PR TITLE
Use 'utf8' encoding to write log file

### PR DESCRIPTION
**Pull request by coolalexhuang**
It will throw encoding error when calling print_control_identifiers() function for some circumstance, add encoding to fix this issue.

### CODE REVIEW

**Comment by coolalexhuang** [comment]
Please review it, thanks.

**Comment by vasily-v-ryabov** [comment]
Hi @coolalexhuang thanks for the attempt and for reporting the issue. It seems it's working with Python 3.x only. If you go to AppVeyor failures and read test logs ("Details" link -> dive into some Python 2.7 run), you may find this traceback:
```python
Traceback (most recent call last):
  File "C:\projects\pywinauto\pywinauto\unittests\test_application.py", line 1067, in test_print_control_identifiers_file_output
    self.dlgspec.print_ctrl_ids(filename=output_filename)
  File "C:\projects\pywinauto\pywinauto\application.py", line 663, in print_control_identifiers
    log_file = open(filename, "w", encoding="utf8")
TypeError: 'encoding' is an invalid keyword argument for this function
```

I would recommend using module `codecs` (`with codecs.open(...)`) which should work for both Pythons. Sorry for late response. Hope it will help to improve the fix.

**Comment by vasily-v-ryabov** [comment]
Also this code should return Windows coding page: `import locale; locale.getpreferredencoding()`.
Maybe it's more useful than "utf-8". At least we used it everywhere till now.

**Comment by vasily-v-ryabov** [comment]
Hi @coolalexhuang are you planning to finish this PR soon? Or we can do it for you. The issue was reported one more time in #583.

**Comment by coolalexhuang** [comment]
> Hi @coolalexhuang are you planning to finish this PR soon? Or we can do it for you. The issue was reported one more time in #583.

Hi @vasily-v-ryabov , sorry for my late reply as I am recently busy on other stuffs, could you help fix it? Thanks.

**Pull request merged**
