### PR TITLE
Merge 'master' into 'atspi'

### PR DESCRIPTION
**Pull request by vasily-v-ryabov**
Let's check that nothing is broken. Merge is hard because some files are moved to subfolders and separated in 'atspi' branch. It was my mistake to make this re-factoring too early.

### CODE REVIEW

**Comment by vasily-v-ryabov** [comment]
This pull request **introduces 1 alert** and **fixes 15** when merging 28b75d352e2e99afe4c2fd91b045a43869648fae into 45ccc02b846748b62d7747c1da67ea9d2a0e02a2 - [view on LGTM.com](https://lgtm.com/projects/g/pywinauto/pywinauto/rev/pr-a44a0fd21a39aba71407724781c246aa96312be6)

**new alerts:**

* 1 for Unused import

**fixed alerts:**

* 12 for Variable defined multiple times
* 2 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by airelil** [comment]
BTW, we'd better add a guard in ```ApplicationTestCases.test__iter__``` to prevent endless loop, because it blocks the execution of the rest of the tests.

**Comment by vasily-v-ryabov** [comment]
This pull request **fixes 15 alerts** when merging d01a4be9b86ad3b0588f3742ef023cefdba4a646 into 45ccc02b846748b62d7747c1da67ea9d2a0e02a2 - [view on LGTM.com](https://lgtm.com/projects/g/pywinauto/pywinauto/rev/pr-7880d2a3d50d111110401544a69361a66f3bd6b1)

**fixed alerts:**

* 12 for Variable defined multiple times
* 2 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by vasily-v-ryabov** [comment]
This pull request **fixes 15 alerts** when merging ce07ac5e2bf6b6f22fd0dbc96934de099bab4eac into 45ccc02b846748b62d7747c1da67ea9d2a0e02a2 - [view on LGTM.com](https://lgtm.com/projects/g/pywinauto/pywinauto/rev/pr-78fba6c77d54a0c2b9c47d539566367021142604)

**fixed alerts:**

* 12 for Variable defined multiple times
* 2 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
