### PR TITLE
Allows Application to be inherited

### PR DESCRIPTION
**Pull request by efremovd**
This will allow to create sub classes of Application class with its own additional methods.

### CODE REVIEW

**Comment by efremovd** [comment]
Yep. Thought about it after. Will do later, where to put it better?

**Comment by cetygamer** [comment]
@efremovd, I guess `/pywinauto/unittests/test_application.py` will do just fine.

**Comment by efremovd** [comment]
@airelil please take a look. Thanks

**Comment by efremovd** [comment]
Could you guys help with those errors from codacy/pr

> No blank lines allowed before class docstring (found 1)
But all tests are written this way

>Method could be a function
How I can tell it that it should be a method (but I don't care about what inside)

**Comment by vasily-v-ryabov** [comment]
@efremovd just remove empty line 610 for the first warning (as I remember it's PEP-257 for doc strings). To workaround the second one, you may return some existing member of Application or just ignore it. Some warnings may look stupid in some situations. PEP-8 says to keep consistency first than fixing everything you see.

**Comment by efremovd** [comment]
I mean really :(

> 1 blank line required before class docstring (found 0)

I just removed it in last commit because before it complains that It should not be there...

**Comment by vasily-v-ryabov** [comment]
Hmm.. It might be a Codacy issue. I've already filed another issue against them (Java checks were done for Python code) so quality of their product is not so stable. Blank line is required before class docstring as we done for other class like [this one](https://github.com/pywinauto/pywinauto/blob/master/pywinauto/controls/uiawrapper.py#L136).

P.S. Some unit tests are also unstable. It's also our pain. Please ignore sporadic failures in AppVeyor tests.
Travis CI failed due to removal of qt58tools from apt-get repo for Ubuntu (looks like new Qt is out). We'll also update it soon. Sorry for confusion and for delayed reply (I'm on vacation for 2 weeks but can reply from time to time).

**Comment by efremovd** [comment]
Are u guys going to merge it? or there is something I need to do?

**Comment by vasily-v-ryabov** [comment]
I'm mostly offline this week. Merged from phone. Will be online this Thursday.

Thanks for your contributions!

**Comment by efremovd** [comment]
I'm sorry. I thought you guys are together merge things :). No problem.

When do you plan to release next version 0.6.XX?

**Comment by vasily-v-ryabov** [comment]
0.6.3 is planned for this week. We can merge together (me and @airelil) except some complicated cases like this when some quality checks are not passed. I want to report this issue to Codacy support team.

**Comment by efremovd** [comment]
Good.

Thanks for you work.

----------
Regards,
Dmitry Efremov.

**Pull request merged**
